language: php
php:
    - 7.0
jdk:
    - oraclejdk7
before_script:
    - wget dist.neo4j.org/neo4j-community-2.2.5-unix.tar.gz
    - tar -xzf neo4j-community-2.2.5-unix.tar.gz
    - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.5/conf/neo4j-server.properties
    - neo4j-community-2.2.5/bin/neo4j start
    - composer install --prefer-source
script: phpunit --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
    slack: innmind:nAiLaAi6RU4wGEAdL6FuKdyF
